#+TITLE: Психология влияния
#+OPTIONS: tex:t 
#+ODT_STYLES_FILE:
#+DESCRIPTION: 
#+KEYWORDS:
#+SUBTITLE: Реферат
#+SETUP: showall
#+LATEX_HEADER:

* Подзаголовок
  Пояснение
  Ключевые тезисы
  Иллюстрирующий текст автора


* 

* 

* 

* 
Моя подруга не является оригинальной в этом использовании
мыслительного стереотипа «дорогое = хорошее» для заманивания в ловушку
стремящихся заключить сделку. Лео Ростен приводит пример братьев
Друбек, Сида и Гарри, которые владели магазином мужского платья по
соседству с Ростеном в то время, когда он был ребенком в 1930-е
годы. Всякий раз, когда у продавца, Сида, появлялся новый
потенциальный покупатель, примеривающий костюмы перед магазинным
трюмо, он напускал на себя вид человека, имеющего проблемы со слухом,
и во время разговора неоднократно просил клиента говорить с ним
погромче. Как только покупатель находил костюм, который ему нравился,
и спрашивал о цене, Сид обращался к брату, главному торговцу мужским
платьем, крича в глубь комнаты: «Гарри, сколько стоит этот костюм?»
Отрываясь от своей работы — и чрезвычайно преувеличивая истинную цену
костюма, Гарри обычно отвечал: «Этот прекрасный костюм из чистой
шерсти стоит сорок два доллара». Делая вид что он не расслышал и
прикладывая руку к уху, Сид спрашивал снова. Гарри опять отвечал:
«Сорок два доллара». В этот момент Сид поворачивался к покупателю и
сообщал: «Он говорит, что костюм стоит двадцать два
доллара». Большинство людей обычно спешили купить костюм и выбраться
из магазина со своей «дорогое - хорошее» покупкой, прежде чем бедный
Сид обнаружит свою «ошибку».






Те, кто хочет применить на практике принцип контраста, могут сделать
это без какого-либо явного структурирования ситуации. Розничные
торговцы тканями и одеждой являются хорошим примером. Предположим,
человек входит в фешенебельный магазин для мужчин и говорит, что хочет
купить костюм-тройку и свитер. Если бы вы были продавцом, что бы вы
показали покупателю сначала, чтобы заставить его наверняка потратить
больше денег? Владельцы магазинов одежды рекомендуют своему персоналу
сначала продавать более дорогие предметы. Здравый смысл может
подсказывать обратное: если человек только что потратил массу денег,
чтобы приобрести костюм, он может отказаться от покупки свитера. Но
торговцы одеждой зн.шт лучше. Они ведут себя в соответствии с
принципом контраста: сначала продайте костюм, потому что когда дело
дойдет до свитеров, даже дорогих, их цены не будут казаться чересчур
высокими на фоне цен костюмов. Человек может внутренне сопротивляться
трате 95 долларов на свитер, но если он только что купил костюм за 495
долларов, свитер за 95 долларов не покажется ему слишком дорогим. Тот
же самый принцип применим к человеку, который хочет купить аксессуары
(рубашку, туфли, ремень) к новому костюму. Вопреки взгляду с позиции
здравого смысла, факты подтверждают действенность принципа
контраста. Как утверждают торговые аналитики Уитни, Хубин и Мэрфи в
книге «Новая психология убеждения и значение мотивации при продаже» 




Умное использование принципа контраста восприятия никоим образом не
ограничивается торговлей одеждой. Я столкнулся с методикой, которая
основывается на этом принципе, когда исследовал тактику «внушения
уступчивости» компаний по торговле недвижимостью. Чтобы «научить меня
что к чему», представитель компании сопровождал меня во время показа
домов перспективным покупателям. Продавец — мы можем называть его
Филом — должен был познакомить меня с основами бизнеса, чтобы помочь в
период привыкания. Вскоре я заметил, что, когда бы Фил ни приступал к
показу клиентам потенциальных покупок, он обычно начинал с пары
неподходящих домов. Я спросил его об этом, и он рассмеялся. Эти дома
были тем, что он назвал собственностью «для показа». Компания включает
один-два запущенных дома в свои списки, причем явно завышая их
цену. Эти дома предназначены не для того, чтобы быть проданными
покупателям, а для того, чтобы только показывать их, так, чтобы
перспективная собственность из каталога компании выигрывала от
сравнения. Не все штатные сотрудники пользовались показными домами, но
вот Фил ими пользовался. Он говорил, что ему нравится наблюдать, как
«загораются глаза» людей, когда он показывает недвижимость, которую
действительно хочет им продать, после того как они увидели запущенные
дома, напоминающие груду хлама.




Субъект, который участвовал в исследовании, должен был оценить
качество ряда картин. Другой оценивающий — мы можем называть его Джо —
только представлялся таким же субъектом, будучи на самом деле
ассистентом доктора Ригана. Эксперимент проводился в двух
модификациях. В одном случае Джо оказывал маленькую непрошеную
любезность истинному испытуемому. Во время короткого перерыва Джо
покидал комнату на пару минут и возвращался с двумя бутылками
«Кока-колы», одной для испытуемого и другой для себя, говоря: «Я
спросил у доктора, можно ли мне взять для себя "Колу", и он разрешил,
так что я купил еще одну для вас». В другом случае Джо не оказывал
испытуемому любезности; он просто возвращался после двухминутного
перерыва с пустыми руками. Во всех остальных отношениях Джо вел себя
одинаково.

Позднее, когда все картины оказывались оцененными и доктор Риган
покидал комнату, Джо просил испытуемого оказать любезность ему. Он
признавался, что продает лотерейные билеты и что если он распространит
большую часть билетов, то выиграет приз в 50 долларов. Джо просил
испытуемого купить несколько лотерейных билетов по цене 25 центов за
штуку: «Пожалуйста, купите любое количество, чем больше, тем лучше». В
ходе исследования было сделано интересное заключение относительно
количества билетов, приобретенных у Джо испытуемыми в двух разных
ситуациях. Без всякого сомнения, Джо с большим успехом продавал
лотерейные билеты тем участникам эксперимента, которые воспользовались
ранее его любезностью. Явно ощущая, что они чем-то обязаны Джо, эти
люди покупали в два раза больше билетов, чем те, кому Джо не оказывал
любезности. 





Некоторые свидетельства того, что влияние правила взаимного обмена
часто оказывается сильнее влияния других факторов, которые обычно
определяют, следует ли исполнять просьбу, можно увидеть в результатах
исследования Ригана. Ригана интересовала не только связь правила
взаимного обмена с уступчивостью, но и то, как симпатия к данному
человеку влияет на склонность подчиниться его требованию. Чтобы
установить, как симпатия к Джо повлияла на решение испытуемых купить
лотерейные билеты, Ри-ган попросил участников эксперимента заполнить
несколько оценочных листов-тестов, показывающих, насколько им нравится
Джо. Затем Риган соотнес выраженность симпатии испытуемых к Джо с
количеством купленных у него билетов. При этом была обнаружена
склонность участников эксперимента покупать тем больше лотерейных
билетов у Джо, чем больше он им нравился. Но это вряд ли является
поразительным открытием. Большинство из нас знает, что люди гораздо
чаще оказывают любезность тем, кто им нравится.

В эксперименте Ригана, однако, связь между симпатией и уступчивостью
не наблюдалась в ситуации, когда испытуемые получали от Джо
«Кока-колу». Для тех, кто был обязан Джо, не имело значения, нравится
он им или нет; они чувствовали, что должны ему каким-то образом
отплатить, и они это делали. Участники эксперимента, отмечавшие, что
Джо им не нравится, покупали у него столько же билетов, сколько те,
кто утверждал, что Джо им нравится. Правило взаимного обмена имело
настолько сильное влияние, что «брало верх» над фактором, который
обычно влияет на решение подчиниться просьбе, — над симпатией к
просителю.









В течение раннего периода современной истории Общества Кришны
вымогательство взносов осуществлялось в необычной форме. Группы
фанатиков-кришнаитов — часто с выбритыми головами, в плохо сидящей
одежде, с обмотками на ногах, с четками и бубенчиками — обычно
собирали пожертвования на городских улицах, монотонно напевая и
пританцовывая в процессе выпрашивания денег.

Хотя такая методика чрезвычайно эффективно способствовала привлечению
внимания, сбор средств шел не очень хорошо. Средний американец считал
кришнаитов по меньшей мере странными и не изъявлял желания давать им
деньги. Членам Общества Кришны быстро стало ясно, что у них
неправильно организована реклама. Людям, у которых кришнаиты
выпрашивали взносы, не нравилось, как члены Общества выглядели и
действовали. Если бы Общество Кришны было обычной коммерческой
организацией, решение было бы простым — изменить то, что не нравится
публике. Но кришнаиты — религиозная организация, и то, как ее члены
одеваются и действуют, отчасти связано с религиозными
факторами. Поскольку в любой конфессии религиозные факторы, как
правило, не меняются по мирским соображениям, руководство Общества
кришнаитов оказалось перед лицом настоящей дилеммы. С одной стороны,
поведение, вид одежды и прически имели большое значение. С другой
стороны, финансовому благополучию организации угрожали отрицательные
взглядь! американской публики. Что же было делать секте?

Решение кришнаитов было блестящим. Они разработали новую тактику сбора
средств. Человеку, на которого они нацеливались, теперь не обязательно
было иметь по отношению к сборщикам средств положительные
чувства. Кришнаиты начали применять процедуру выпрашивания взносов,
основанную на правиле взаимного обмена, которое, как
продемонстрировало исследование Ригана, является достаточно «могучим»,
чтобы преодолеть фактор неприязни к тому, кто обращается с
просьбой. Новая стратегия кришнаитов, так же как и прежняя, включает в
себя выпрашивание подачек в публичных местах с интенсивным пешеходным
движением (аэропорты являются излюбленными местами), но теперь, прежде
чем попросить человека о пожертвовании, кришнаиты вручают ему
«подарок» — книгу (обычно «Бхагават Гита»), журнал Общества «Назад к
Богу» (Back to the Godhead) пли, что наиболее просто и дешево,
цветок. Ничего не подозревающему прохожему, который внезапно
обнаруживает, что ему в руки сунули цветок, ни в коем случае нельзя
разрешить вернуть этот цветок, даже если человек утверждает, что он
ему не нужен. «Нет, это наш подарок вам», — говорит сборщик
пожертвований, отказываясь принять цветок обратно. Только после того,
как член Общества кришнаитов таким образом задействует правило
взаимного обмена, прохожего просят сделать пожертвование в пользу
Общества. Эта стратегия оказалась фантастически эффективной и принесла
Обществу Кришны крупномасштабную прибыль, позволившую профинансировать
деятельность многочисленных храмов и предприятий, а также приобрести
собственность в 321 городе в Соединенных Штатах и других странах.





Исследователи, проводящие опросы общественного мнения, обнаружили, что
если к опроснику изначально приложить денежное вознаграждение
(серебряный доллар или чек на 5 долларов), вместо того чтобы
перечислять вознаграждение по факту получения заполненного вопросного
листа, то эффективность опроса резко возрастает (Church, 1993;
Warriner, Goyder, Gjertsen, Homer & McSpurren, 1996). В одном
исследовании было доказано, что «вознаграждение» в виде
пятидолларового чека, приложенного к анкете по страхованию, приносит
вдвое больший результат, чем выплата 50 долларов после того, как
заполненная анкета была отправлена назад (James & Bolsten,
1992). Аналогичным образом поступают официанты, когда к счету
прикладывают «подарок» — конфету или жевательную резинку — что
значительно увеличивает размер чаевых (Gruner, 1996).






Рассмотрим случай с шумихой, развернувшейся вокруг одного
лекарственного препарата против болезней сердца, вопрос безопасности
которого для здоровья стал предметом бурных дискуссий. Расследование
доказало, что 100% ученых, написавших статьи в защиту препарата,
пользовались разными видами «поддержки» (международные командировки,
выделение средств на эксперименты, предоставление персонала) от
фармацевтических компаний; но из тех, кто отозвался о препарате
критически, «поддержку» получали только 37 % (Stelfox, Chua, O'Rourke
& Detsky). 






Правило взаимного обмена «правит бал» и в межличностных отношениях,
когда речь не идет ни о деньгах, ни о коммерческом обмене. Здесь будет
уместно привести следующий пример. Европейский ученый Айбл-Айбсфельдт
(Eibl-Eibesfeldt, 1975) поведал миру историю одного немецкого солдата,
основной задачей которого во время Первой мировой войны была поимка
вражеских солдат для допроса. Из-за специфики окопных боевых действий
того времени армиям было чрезвычайно трудно пересекать ничейную
территорию между линиями фронтов; но отдельному солдату было несложно
пробраться ползком и незаметно проскользнуть в окоп противника. В
армиях имелись специалисты, которые регулярно проделывали это, чтобы
захватить в плен вражеского солдата. Германский специалист, о котором
идет речь в нашем рассказе, часто успешно выполнял подобные
миссии. Однажды он ловко преодолел расстояние между фронтами и застиг
врасплох солдата во вражеском окопе. Ничего не подозревающий солдат в
это время ел и поэтому был легко обезоружен. Испуганный пленник с
одним лишь куском хлеба в руках затем сделал то, что, возможно, было
самым важным поступком в его жизни. Он протянул своему врагу
хлеб. Немец был так тронут этим подарком, что не смог выполнить свое
задание. Он предпочел вернуться в свою часть с пустыми руками, не
побоявшись гнева начальства.

Интересен и другой пример. Одна женщина спасла свою жизнь не тем, что
сделала подарок, как захваченный солдат, а тем, что отказалась от
подарка и от тяжелых обязательств, которые были с ним связаны. Эта
женщина, Дайана Луи, была жительницей Джонстауна в Гайане. В ноябре
1978 года глава общины Джим Джонс призвал к массовому самоубийству
всех жителей, большинство которых с готовностью выпили из цистерны
Kool-Aid* с добавлением яда и умерли. Дайана Луи, однако, отказалась
выполнять приказ Джонса и ушла из Джонстауна в джунгли. Она объясняет
свой протест предшествовавшим ему отказом принять особые милости от
Джонса. Будучи больной, Дайана отвергла предложенную Джонсом особую
еду, потому что «знала, что как только он мне предоставит эти
привилегии, он меня поймает. Я не хотела быть ему обязанной хоть
чем-нибудь» (Anderson & Zimbargo, 1984).








Чисто случайно я оказался свидетелем сцены, которая показывает, что
кришнаиты очень хорошо знают, насколько часто их подарки бывают
ненужными. Несколько лет назад, наблюдая за группой кришнаитов в
чикагском международном аэропорту имени О'Хары, я обратил внимание на
то, что одна девушка часто оставляла группу и возвращалась с цветами,
которыми снабжала своих компаньонов. Я решил проследить за этой
девушкой. Оказалось, что ее интересовало содержимое мусорных
бачков. Она переходила от одного мусорного контейнера к другому и
собирала цветы, которые были выброшены теми, кто оказался в поле
внимания кришнаитов. Затем девушка вернулась с ворохом цветов
(некоторые цветы, таким образом, были использованы несколько раз) и
распределила их среди своих компаньонов. Особенно сильное впечатление
на меня произвело то, что большая часть тех людей, которые выбросили
цветы, пожертвовали деньги. Природа правила взаимного обмена такова,
что даже совершенно ненужный подарок, от которого спешат отделаться
при первой же возможности, тем не менее «работает».









Как-то раз я прогуливался по улице, и вдруг ко мне подошел
одиннадцати- или двенадцатилетний мальчик. Он представился и сказал,
что продает билеты на ежегодное представление бойскаутов, которое
состоится вечером в ближайшую субботу. Мальчик спросил, не хочу ли я
купить несколько билетов по пять долларов за штуку. Поскольку
представление бойскаутов было не тем мероприятием, которое мне
хотелось бы посетить в субботний вечер, я отказался. «Хорошо, — сказал
мальчик, — если вы не хотите купить билеты, как насчет больших плиток
шоколада? Они всего лишь по доллару за штуку». Я купил пару и
немедленно осознал, что случилось нечто заслуживающее внимания, потому
что: а) я не люблю шоколад; б) я люблю доллары; в) я остался с двумя
ненужными мне шоколадными плитками; г) мальчик ушел с моими двумя
долларами.










Немного подумав, мы решили испробовать эту методику на практике. Мы
придумали требование, выполнить которое, как нам казалось, согласились
бы немногие. Выдавая себя за представителей «Молодежной
консультационной программы графства», мы подходили к студентам
колледжа, прогуливавшимся по кампусу, и спрашивали, не согласятся ли
они сопровождать группу несовершеннолетних преступников во время
прогулки по зоопарку. Предложение на несколько часов взять на себя
ответственность за группу несовершеннолетних преступников вряд ли
могло привлечь студентов. Как мы и ожидали, подавляющее большинство
(83 %) молодых людей отказались. Однако мы получили совершенно другие
результаты, когда изменили форму вопроса. Прежде чем предложить
студентам бесплатно поработать сопровождающими, мы просили их о более
сложной услуге — каждую неделю давать консультации несовершеннолетним
преступникам в течение как минимум двух лет. Только после того как
студенты отказывались выполнить это чрезвычайно тяжелое требования (а
отказывались все), мы предъявляли менее серьезное требование — сходить
с несовершеннолетними преступниками в зоопарк. Представляя поездку в
зоопарк в качестве отступления от первоначального запроса, мы добились
поразительных успехов. В три раза большее число студентов, к которым
мы обращались, добровольно согласились сопровождать группу юных
преступников (Cialdini, Vincent, Lewis, Catalan, Wheeler & Darby,
1975).








Некоторые из наиболее преуспевающих телевизионных продюсеров, такие
как Грант Тинкер и Гэри Маршал (Grant Tinker, Garry Marshall),
преуспели в использовании данной методики в переговорах с цензорами
телесети. В одном интервью они оба чистосердечно признались в том, что
сознательно вставляют в сценарии строки, которые цензор наверняка
вычеркнет, чтобы сохранить действительно нужные строки. Маршал
выглядел особенно активным в этом отношении. Обратите внимание на
следующие цитаты из статьи о нем Дика Рассела (Russell, 1978).

Но Маршал... не только признается в своих трюках... он, похоже,
получает от них удовольствие. Об одном эпизоде своего популярного
сериала «Лаверн и Ширли» (Laverne and Shirley) он говорит так: «У нас
была задумана следующая сцена: Сквигги в спешке выбегает из своей
комнаты и встречается с девушками, живущими наверху. Он спрашивает их:
"Не поторопитесь ли вы, пока мое возбуждение не прошло?" Но в сценарий
мы включили еще более "сильную" фразу, зная, что цензоры ее
вырежут. Они действительно ее вырезали. Тогда мы невинно предложили им
второй вариант. "Это подойдет", — сказали они. Иногда приходится идти
окольными путями».

Во время работы над сериалом «Счастливые дни» (Happy Days) началась
настоящая война с цензорами из-за слова «девственница». Маршал
говорит: «Я знал, что у нас будут проблемы, поэтому мы вставили это
слово семь раз, надеясь, что в шести случаях его вырежут, а в одном —
оставят. Это сработало. Мы снова использовали эту тактику, когда надо
было сохранить слово "беременная"».










Исследователи инсценировали кражи на нью-йоркском городском пляже,
чтобы посмотреть, пойдут ли посторонние наблюдатели на риск навлечь на
себя неприятности, чтобы не дать совершиться преступлению. Участник
эксперимента располагал свой пляжный коврик недалеко от коврика
какого-либо отдыхающего, доставал портативный радиоприемник, а затем
отправлялся прогуляться по пляжу. Вскоре после этого другой участник
эксперимента, изображая вора, подходил к радиоприемнику, хватал его и
пытался с ним удрать. Как вы можете догадаться, в большинстве случаев
люди очень неохотно вмешивались — в 20 случаях инсценировки кражи
только четыре человека сделали это. Однако при некотором изменении
условий проведения опыта результаты радикально изменились. Теперь,
перед тем как отправиться на прогулку, участник эксперимента просил
соседа «присмотреть за вещами», на что согласен любой. Стремясь быть
последовательными, в 19 из 20 случаев люди кидались за вором,
останавливали его, требуя объяснения, или выхватывали у него
радиоприемник (Moriarty, 1975).










Исследователь Дэниэл Ховард (Howard, 1990), изучающий психологию
потребителя, проверил эту теорию. Жителям Далласа, штат Техас, звонили
по телефону и спрашивали, разрешат ли они представителям Комитета по
ликвидации голода прийти к ним домой, чтобы продать домашнее печенье,
причем выручка от этой акции будет использована для приобретения
продуктов питания для нуждающихся. Когда эта просьба была высказана
сама по себе, только 18 % опрошенных согласились. Однако если
звонивший предварительно спрашивал: «Как вы себя чувствуете сегодня
вечером?» и дожидался ответа, прежде чем перейти к дальнейшему
изложению вопроса, отмечались заслуживающие внимания
моменты. Во-первых, из 120 человек, к которым обратились психологи,
большинство (108) на вопрос о самочувствии ответили положительно
(«Хорошо», «Прекрасно» и т. п.). Во-вторых, 32 % людей, ответивших
таким образом, согласились принять продавцов печенья у себя дома (это
почти вдвое больше, чем при стандартном подходе). В-третьих, верные
принципу последовательности, почти все (89 %) согласившиеся на визит
купили печенье.







В небольшом городке в Калифорнии был проведен эксперимент, в ходе
которого исследователь, выдающий себя за добровольца, ходил по домам и
предъявлял нелепое требование к домовладельцам. Их просили разрешить
разместить на парадных лужайках доски для афиш и объявлений,
предназначенные для общественного пользования. Чтобы хозяева домов
получили представление о том, как могла бы выглядеть надпись, им
показывали фотографию с изображением красивого дома, который был почти
полностью закрыт огромной неаккуратной вывеской, гласившей «ВЕДИТЕ
МАШИНУ ОСТОРОЖНО». Хотя данное требование по понятным причинам
отвергалось подавляющим большинством (согласились только 17 %) других
жителей этого района, данная конкретная группа людей реагировала
достаточно благосклонно (76 % домовладельцев разрешили воспользоваться
своими дворами).

Фридман и Фрезер не остановились на этом. Они испытали свою методику в
несколько иной модификации. Сначала домовладельцев попросили подписать
обращение, которое призывало «содержать Калифорнию в
чистоте». Конечно, почти все подписали, поскольку чистота окружающей
среды, так же как справедливость правительства или гигиена
беременности, — это один из тех вопросов, против которых почти никто
не выступает. Подождав две недели, Фридман и Фрезер послали нового
«добровольца» в эти же самые дома просить разрешения разместить на
лужайках плакат «ВЕДИТЕ МАШИНУ ОСТОРОЖНО». К удивлению исследователей,
приблизительно половина домовладельцев согласились на установку этого
плаката, хотя небольшое обязательство, которое они взяли на себя двумя
неделями ранее, относилось к заботе не о безопасности уличного
движения, а о чистоте штата.









Известные социальные психологи Мортон Дойч и Гарольд Джерард (Deutsch
& Gerard, 1955) провели интересное исследование. Целью этого
исследования было изучение связи между публично данными
обязательствами и последовательностью действий. Студентов колледжа
просили оценить длину линий, которые им показывали. Одни студенты
должны были публично высказать свои предположения, записать их,
указать свои имена и передать эти отчеты экспериментатору. Студенты из
второй группы также давали оценку, но они делали это про себя. Каждый
записывал свою оценку в «волшебный» блокнот и затем стирал запись
путем поднятия пластиковой обложки блокнота прежде, чем кто-либо мог
увидеть написанное. В третьей группе студенты просто запоминали свои
оценки.

Таким образом, Дойч и Джерард организовали дело так, что одни студенты
приняли на себя обязательства в отношении своих первоначальных решений
публично, другие — частным образом, третьи же вовсе не взяли никаких
обязательств. Дойч и Джерард хотели выяснить, студенты какой из трех
групп будут крепче держаться за свои первоначальные суждения после
того, как станет известно, что эти суждения были неверными. Всем
студентам объявили, что их оценки были неправильными, после чего
студентам был дан шанс изменить свои мнения.

Были получены следующие результаты. Студенты, которые не записывали
свои первоначальные варианты, оказались наименее верны себе. Новая
информация побудила их изменить свои решения. По сравнению с этими не
имевшими обязательств студентами, те, кто записал свои решения на
мгновение в «волшебный» блокнот, были в меньшей степени готовы
изменить свое мнение, когда получили такой шанс. Хотя студенты из
второй группы принимали на себя обязательства без свидетелей, акт
записи суждений заставлял их сопротивляться влиянию новой информации и
оставаться верными себе. Студенты, которые публично заявили о своих
позициях и затем записали свои оценки, наиболее решительно
отказывались изменить мнение.




В кампусах некоторых колледжей должностные лица попытались уничтожить
порочную практику злого подшучивания над новичками путем замены Адской
недели на Неделю помощи гражданской службы или установления
непосредственного контроля над ритуалами посвящения. Подобные попытки
властей члены братств обычно хитро обходят или встречают открытым
физическим сопротивлением. Например, после смерти от удушья Ричарда
Свенсона в университете Южной Калифорнии ректор университета издал
новые правила, согласно которым вся деятельность братств должна
контролироваться администрацией и на церемониях посвящения должны
присутствовать взрослые советники. Как было отмечено в одном из
национальных журналов, «новый кодекс вызвал настолько ожесточенный
бунт, что городская полиция и команда пожарных побоялись войти в
кампус».

Смиряясь с неизбежным, другие преподаватели признали свое бессилие в
борьбе с организаторами Адской недели. «Если злое подшучивание над
новичками является неотъемлемой составляющей человеческой
деятельности, а все известные факты подводят к подобному заключению,
едва ли вы будете в состоянии запретить его. Если вы не разрешите
молодым людям действовать открыто, они будут вынуждены "уйти в
подполье". Вы не можете запретить секс, не можете запретить алкоголь и
точно так же не можете запретить злое подшучивание над новичками!»
(Gordon & Gordon, 1963).





Фридман хотел выяснить, сможет ли он помешать мальчикам в возрасте от
семи до девяти лет играть с интересной игрушкой, сказав шестью
неделями ранее, что делать это дурно. Любой человек, имевший дело с
такими мальчиками, должен понять грандиозность задачи. Но у Фридмана
был план. Сначала, по мнению исследователя, надо было добиться, чтобы
мальчики убедили самих себя в том, что играть с запрещенной игрушкой
дурно. Возможно, думал Фридман, это убеждение удержит детей от игры с
ней впоследствии. Но как заставить мальчиков поверить, что дурно
играть с дорогим, работающим на батарейках роботом?

Фридман знал, что довольно просто заставить ребенка повиноваться в
течение короткого времени. Все, что для этого следовало сделать, это
пригрозить мальчику суровым наказанием за игру с запрещенной
игрушкой. Фридман полагал, что, находясь под его наблюдением, немногие
мальчики рискнули бы играть с роботом. Он был прав. Фридман показывал
мальчику пять игрушек и говорил следующее: «Играть с роботом
дурно. Если ты будешь это делать, я очень сильно рассержусь и буду
вынужден наказать тебя». Затем Фридман покидал комнату на несколько
минут. За мальчиком тайно велось наблюдение через одностороннее
зеркало. Фридман испытал эту процедуру с угрозой на 22 разных
мальчиках, и 21 из них не прикоснулся к роботу.

Таким образом, угроза «работала», до тех пор пока мальчики думали, что
их могут поймать и наказать. Именно такой результат Фридман и
предвидел. Он хотел узнать, будет ли действовать угроза позднее, когда
его не будет рядом. Чтобы выяснить это, Фридман послал молодую
женщину, своего ассистента, в школу к мальчикам через шесть недель
после того, как он там был. Женщина-ассистент забирала мальчиков из
класса по одному и проводила с ними эксперимент. Даже не упоминая о
своем знакомстве с Фридманом, она вводила каждого мальчика в комнату с
игрушками и давала ему тест по рисованию. Помощница Фридмана говорила
мальчику, что он может брать любую игрушку в комнате, пока она
оценивает тест. Интересно, что 77 % мальчиков остановили свой выбор на
роботе, который ранее был для них «запретным плодом». Угроза Фридмана,
которая так хорошо «работала» шесть недель тому назад, почти не
действовала, когда он больше не мог подкрепить ее наказанием.

Но Фридман не остановился на этом. Он несколько изменил процедуру со
вторым набором мальчиков. Этим мальчикам Фридман также сначала
показывал пять игрушек и делал аналогичное предупреждение. На этот раз
Фридман не запугивал мальчиков с целью добиться от них повиновения. Он
просто покидал комнату и наблюдал за детьми через одностороннее
зеркало. Оказалось, что указания было достаточно. Так же как и в
первом эксперименте, только один мальчик из 22 коснулся робота за
краткий период отсутствия Фридмана.

 
Различия в поведении мальчиков из первого и второго набора проявились
через |шесть недель, когда мальчикам была предоставлена возможность
выбирать игрушки I;' В отсутствие Фридмана. С мальчиками, которым
ранее не угрожали, чтобы заставить 1 их не играть с роботом, случилась
поразительная вещь: несмотря на разрешение иг-н рать с любой игрушкой,
большинство мальчиков избегали робота, хотя это была самая
привлекательная из имевшихся в комнате игрушек (другими были дешевая
пластиковая подводная лодка, детская бейсбольная перчатка без мяча,
незаряженное игрушечное ружье и игрушечный трактор). Только 33 %
мальчиков из второго набора предпочли робота.

Мальчики из первого набора подверглись внешнему давлению. Этим
давлением являлась угроза, которую они услышали от Фридмана в
дополнение к его заявлению о том, что играть с роботом «дурно». Угроза
довольно хорошо «работала», когда Фридман мог поймать ослушавшихся
мальчиков. Однако позднее, когда он уже не наблюдал за мальчиками, его
угроза перестала действовать и мальчики начали игнорировать
запрет. Очевидно, угроза не убедила мальчиков в том, что играть с
роботом дурно; они лишь поняли, что делать это неразумно, когда
существует опасность наказания.

У мальчиков из второго набора своего рода давление возникло изнутри, а
не извне. Фридман также говорил им, что играть с роботом дурно, но он
не угрожал мальчикам наказанием в случае непослушания. В результате
произошло следующее. Во-первых, одного только указания Фридмана
оказалось достаточно для того, чтобы мальчики не начинали приводить
робота в действие, пока Фридман на короткое время покидал
комнату. Во-вторых, мальчики приняли на себя личную ответственность за
свое решение не трогать робота в течение этого времени. Дети решили,
что они не делали этого, потому что они не хотели. В данном случае не
было никакой угрозы, которая могла бы объяснить поведение
мальчиков. Спустя шесть недель, когда Фридмана рядом не было, они
по-прежнему игнорировали робота, потому что изменились изнутри, убедив
себя в том, что не хотят с ним играть.





Определенным покупателям предлагается цена, которая примерно сотни на
четыре ниже, чем цены у конкурентов. Однако продавец никогда не даст
состояться подобной сделке. Единственная цель такого заманчивого
предложения — заставить предполагаемого клиента решить купить
машину. Как только покупатель принимает решение, продавец начинает
совершать ряд действий, направленных на то, чтобы вызвать у покупателя
чувство личной ответственности в отношении данной машины — заполняется
множество различных форм, подробно оговариваются условия
финансирования, иногда покупателю предлагают в течение дня поездить на
новой машине до подписания контракта, «чтобы вы могли ее почувствовать
и показать окружающим в действии». Опытный дилер знает, что в течение
этого времени покупатель автоматически сформулирует для себя ряд новых
доводов, поддерживающих выбор, который он сделал, и оправдывающих
вложения, которые он сейчас делает (Brockner & Rubin, 1985; Teger,
1980).

Затем что-то случается. Иногда открывается «ошибка» в подсчетах —
возможно, торговец «забыл» добавить стоимость кондиционера, и если
покупатель нуждается в кондиционировании воздуха, он должен добавить
четыре сотни долларов к цене. Чтобы не дать покупателю заподозрить
надувательство, некоторые дилеры позволяют банку, с которым они
работают, обнаруживать «ошибку». В других случаях сделка аннулируется
в последний момент, когда продавец якобы обсуждает ее условия с
боссом, который расценивает сделку как невыгодную и отменяет
ее. Машину можно получить, только заплатив дополнительные четыре сотни
долларов, которые в контексте сделки на многие тысячи долларов не
выглядят чрезмерной тратой. К тому же торговец подчеркивает, что цена
не выше, чем в других агентствах, и «Это ведь машина, которую вы
выбрали, верно?» Другая, еще более изощренная модификация тактики
«выбрасывания низкого мяча» имеет место, когда торговец предлагает
клиенту отдать старую машину в счет платы за новую. Покупатель
признает это предложение слишком благородным и хватается за
него. Позднее, перед самым подписанием контракта, менеджер по покупке
подержанных машин говорит, что оценка продавцом старой машины на
четыре сотни завышена и, следовательно, новая машина обойдется клиенту
в сумму, указанную в справочнике для автомобилистов. Покупатель,
считая, что урезанное предложение является честным, соглашается на
него и иногда даже . испытывает чувство вины из-за своего желания
извлечь выгоду из промаха торговца. Я однажды был свидетелем того, как
женщина смущенно извинялась перед продавцом, который применил к ней
описанную модификацию тактики «выбрасывание низкого мяча» — все это в
тот момент, когда она подписывала контракт о покупке новой машины, тем
самым давая агенту колоссальное комиссионное вознаграждение. Продавцу
явно было не по себе, но он выдавил из себя прощающую улыбку.














Альберт Бандура занимался разработкой способов изменения нежелательных
моделей поведения. Бандура и его коллеги доказали, что можно избавить
страдающих фобиями людей от их страхов потрясающе простым
способом. Например, маленьким детям, боявшимся собак, Бандура
(Bandura, Grusec & Menlove, 1967) предложил просто наблюдать за
мальчиком, который весело играл с собакой, по 20 минут в день. Этот
наглядный показ привел к таким заметным изменениям в реакциях пугливых
детей, что после четырех «сеансов наблюдения» 67 % ребят выразили
готовность забраться в детский манеж с собакой и оставаться там,
лаская и почесывая ее, причем даже в отсутствие взрослых. Более того,
когда исследователи через месяц снова оценили уровни страха у этих
детей, они выяснили, что улучшение за этот период не исчезло;
фактически дети охотнее, чем когда-либо, «общались» с собаками. Важное
практическое открытие было сделано в ходе второго исследования Бандуры
(Bandura & Menlove, 1968). На этот раз были взяты дети, которые
особенно боялись собак. Для того чтобы уменьшить их страхи, были
использованы соответствующие видеоролики. Их показ оказался таким же
эффективным, как реальная демонстрация смелого мальчика, играющего с
собакой. Причем наибольшую пользу принесли те ролики, в которых было
показано несколько детей, играющих со своими собаками. 










Большое значение имеет одежда. Проведенные исследования показали, что
мы охотнее оказываем помощь тем, кто одет, как мы. В начале 1970-х
годов, когда в моду вошел стиль «хиппи», был проведен следующий
эксперимент. Несколько исследователей, одни из которых были одеты
традиционно, а другие — в стиле «хиппи», просили у студентов колледжа
10 центов, чтобы позвонить по телефону. Когда экспериментатор был одет
так же, как студент, требование выполнялось более чем в двух третях
случаев; когда же студент и требующий были одеты по-разному, студенты
давали 10 центов менее чем в половине случаев (Emswiller, Deaux &
Willits, 1971). Другой эксперимент показал, насколько автоматической
может быть наша реакция на похо-жих на нас людей. Участники
антивоенной демонстрации не только охотнее подписывали петицию,
предъявлявшуюся им человеком, одетым так же, как и они, но делали это,
даже не потрудившись сначала ознакомиться с содержанием данной петиции
(Suedfeld, Bochner & Matas, 1971).









 Тридцать лет назад родившийся в Турции социолог Музафер Шериф и его
 коллеги (Sherif, Harvey, White, Hood & Sherif, 1961) заинтересовались
 проблемой межгрупповых конфликтов. Шериф и его исследовательская
 команда решили провести несколько исследований в летних лагерях для
 мальчиков. Мальчики даже не подозревали о том, что они являлись
 участниками эксперимента. Шериф и его ассистенты меняли условия жизни
 в лагере и пытались выяснить, как различные социальные изменения
 влияют на отношения между группами.

Как выяснили исследователи, для того чтобы вызвать у детей чувство
взаимной неприязни, потребовалось не много. Простого распределения
мальчиков по двум жилым помещениям оказалось достаточно, чтобы
возбудить у членов разных групп чувство «мы против них», а присвоение
этим двум группам названий («Орлы» и «Гремучие змеи») усилило чувство
соперничества. Мальчики начали принижать достижения другой группы и
высмеивать ее членов. Однако по-настоящему страсти разгорелись тогда,
когда экспериментаторы сознательно ввели во взаимодействие мальчиков
элементы конкурентной деятельности. Охота за сокровищами, игра «хижина
против хижины», перетягивание каната, атлетические соревнования
привели к появлению обидных прозвищ и к конфронтации. Во время
соревнований членов чужой команды обзывали «мошенниками», «трусами» и
«вонючками». Совершались налеты на хижины «врагов», похищались и
сжигались знамена соперников, развешивались угрожающие надписи,
обычным явлением стали потасовки в столовой.

Шерифу вскоре стало ясно, что вызвать у мальчиков ненависть друг к
другу необычайно легко. Для этого достаточно просто разделить
мальчиков на группы и дать им немного повариться в собственном
соку. Затем следует вызвать у них стремление к конкуренции. В
результате мы будем иметь дело с бурлящей перекрестной групповой
ненавистью.

Затем перед экспериментаторами встала более сложная задача —
ликвидировать укоренившуюся враждебность. Исследователи стали часто
организовывать общие отрядные встречи, коллективные просмотры фильмов
и другие подобные мероприятия. Результаты были ужасными даже тогда,
когда эта совместная деятельность носила приятный характер
(кинофильмы, общественные события). Пикники заканчивались сражениями,
в которых пища использовалась в качестве метательных снарядов, во
время вечеров отдыха устраивались шумные потасовки, очереди в столовой
превращались в место проведения соревнований по выталкиванию
соперников. Шерифу и его ассистентам начало казаться, что они, подобно
доктору Франкенштейну, создали чудовище, которое не в состоянии
контролировать. К счастью, в один из самых напряженных моментов они
испробовали стратегию, которая была одновременно простой и
эффективной.

Была смоделирована серия ситуаций, в которых конкуренция между
группами принесла бы вред всем, а сотрудничество привело бы к
получению взаимной выгоды. Во время продолжавшейся весь день экскурсии
было «обнаружено», что единственный автомобиль, на котором можно было
привезти продукты из города, застрял в придорожной канаве. Мальчики
собрались вместе и толкали автомобиль до тех пор, пока он не оказался
на дороге. В другом случае исследователи организовали перерыв в
снабжении лагеря водой, которая поступала по трубам из отдаленного
резервуара. Понимая необходимость объединения усилий в возникшей
чрезвычайной ситуации, мальчики сами нашли решение проблемы и
реализовали его до конца дня. В третьем случае исследователи сообщили
мальчикам, что за прокат любимого всеми фильма требуется заплатить
сумму, которую лагерь не может себе позволить. Понимая, что спасти
положение можно только посредством объединения финансовых ресурсов,
мальчики внесли свои личные деньги в общий фонд. В результате они
провели необыкновенно приятный вечер в компании друг друга.

Полученные результаты воодушевили исследователей. Успешные
объединенные усилия, направленные на достижение общих целей, положили
конец расколу и вражде между группами. Вскоре прекратились словесные
баталии, толкотня в очередях, мальчики начали «перемешиваться» за
обеденными столами. Когда исследователи попросили мальчиков
перечислить имена своих лучших друзей, большинство детей назвали имена
мальчиков из бывшей «чужой» группы; раньше же мальчики считали
друзьями только членов своей группы









Во время одного эксперимента, проводившегося в пяти классах
австралийского колледжа, некоего человека представили как гостя из
Англии, работающего в Кембриджском университете. Однако в каждом
классе его статус в Кембридже был представлен по-разному. В одном
классе человек был представлен как студент, во втором классе — как
лаборант, в третьем классе — как лектор, в четвертом классе — как
старший лектор и, наконец, в пятом классе — как профессор. После того
как человек покидал учебную комнату, учащихся в каждом классе просили
оценить его рост. Было выяснено, что при каждом повышении статуса
«английский гость» вырастал в глазах студентов в среднем на полдюйма,
так что в качестве «профессора» он выглядел на два с половиной дюйма
выше, чем в качестве «студента» (P. R. Wilson, 1968). Другое
исследование показало, что после победы на выборах рост политиков
становится выше в глазах избирателей (Higham & Garment, 1992).













Один из исследователей позвонил на 22 медсестринских поста,
находящихся в хирургических, терапевтических, педиатрических и
психиатрических отделениях больниц. Исследователь представлялся
больничным врачом и приказывал отвечавшей по телефону медицинской
сестре ввести 20 миллиграммов наркотика «Астроген» (Astro-gen) одному
из пациентов, находившихся в отделении. Медицинских сестер должны были
бы насторожить четыре следующих момента: 1) распоряжение было отдано
по телефону, что являлось прямым нарушением больничных правил; 2) само
лечебное средство было неразрешенным, поэтому его не было в больничном
аптечном пункте; 3) предписанная доза была, вне всяких сомнений,
чрезмерной: аннотация на стандартной упаковке данного лекарственного
средства утверждала, что максимальная разовая доза — 10 миллиграммов,
половина того, что было назначено; 4) распоряжение было отдано
человеком, которого ни одна из медицинских сестер никогда раньше не
встречала и с которым ни одна из них даже не разговаривала по
телефону. Однако в 95 % случаев медицинские сестры отправлялись в
указанный медицинский кабинет, брали там назначенную пациенту дозу
«Астрогена» и направлялись в нужную палату, чтобы ввести больному это
лекарство. Именно в этот момент незаметно наблюдавший за медсестрами
исследователь останавливал их и рассказывал им о цели эксперимента
(Honing, Brotzman, Dalrymple, Graves & Pierce, 1966).

Конечно, результаты пугающие. То, что 95 % медицинских сестер из
постоянного больничного штата не колеблясь выполнили явно ошибочное
указание такого рода, наводит на мысль о том, что оказаться на
больничной койке просто страшно — слишком велика вероятность того, что
каждый из нас может стать жертвой врачебной ошибки. Данное
исследование показало, что ошибки не сводятся к неточностям при
назначении безвредных ушных капель или других подобных безобидных
средств, но часто являются серьезными и опасными для жизни
пациентов. Исследователи пришли к следующему выводу.
















Интересно, что два рассмотренных выше типа «авторитетной одежды» —
форма охранника и деловой костюм — искусно сочетаются мошенниками в
так называемой схеме банковского эксперта. Жертвой подобного
мошенничества может стать кто угодно, но чаще всего страдают одинокие
пожилые люди. Операция начинается, когда человек в строгом деловом
костюме-тройке появляется у дверей потенциальной жертвы. Все в одежде
мошенника внушает мысль о пристойности и респектабельности. Белая
рубашка накрахмалена; башмаки с узкими носами сияют. Его костюм не
ультрамодный, а скорее классический: лацканы шириной три дюйма — не
больше и не меньше; сукно тяжелое и прочное (хотя дело может
происходить в июле); тона приглушенные — синий, темно-серый, черный.

Посетитель объясняет своей предполагаемой жертве — возможно, одинокой
вдове, за которой он тайно следовал от дверей банка до ее дома за день
или два до этого, — что он является профессиональным банковским
экспертом, который в ходе проводившейся им экспертизы обнаружил
некоторые неточности в финансовых отчетах. Он подозревает в подделке
отчетов, связанных с определенными счетами, одного банковского
служащего. Человек в костюме говорит, что счет вдовы, возможно, имеет
отношение к махинациям, но чтобы можно было говорить об этом с
уверенностью, необходимо получить доказательства. По этой причине он
пришел просить ее о сотрудничестве. Не согласится ли она снять со
счета свои сбережения, чтобы группа экспертов и ответственные
банковские работники смогли проследить за действиями подозреваемого?
Часто внешний вид и манера держаться «банковского эксперта» бывают
настолько впечатляющи, что жертве даже не приходит в голову мысль
подвергнуть сомнению его слова и хотя бы по телефону получить им
подтверждение. Вместо этого она отправляется в банк, снимает со счета
все свои деньги и возвращается с ними домой, чтобы дожидаться вместе с
«экспертом» сообщения о результатах операции. После того как банк
закрывают, является одетый в униформу «банковский охранник», который
объявляет, что все в порядке — видимо, счет вдовы не имел отношения к
подделке финансовых отчетов. «Эксперт» облегченно вздыхает, любезно
благодарит клиентку банка и дает охраннику указание вернуть деньги
леди в сейф, чтобы избавить ее от необходимости делать это на
следующий день, когда банк откроют. Улыбаясь и пожимая руки жертве,
охранник забирает деньги и оставляет «эксперта» высказывать
благодарности еще в течение нескольких минут. Естественно, как в
конечном счете выясняет жертва, «охранник» не в большей степени
охранник, чем «эксперт» — эксперт. Они на самом деле являются парой
мошенников, которые хорошо знают, что гщательно подобранная униформа
способна оказывать на людей гипнотизирующее воздействие и заставлять
их подчиняться «авторитетам».




